version: '3.9'
services:

  api01: &api
    hostname: api01
    container_name: rinha-2024Q1-api01
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '80MB'
    networks:
      - rinha-default
    environment:
      - PHP_VERSION="8.2"
      - DB_HOST=db
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - DB_NAME=rinha
    volumes:
      - ./src:/application

  api02:
    <<: *api
    hostname: api02
    container_name: rinha-2024Q1-api02

  nginx:
    image: nginx:latest
    container_name: rinha-2024Q1-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    networks:
      - rinha-default
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

  db:
    container_name: rinha-2024Q1-db
    image: postgres:15.4
    environment:
      POSTGRES_DB: 'rinha_backend_2024_q1'
      POSTGRES_PASSWORD: 'rinha'
      POSTGRES_USER: 'rinha'
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'log_statement=none' -c 'log_min_messages=panic' -c 'shared_buffers=256MB' -c 'effective_cache_size=1GB'
    networks:
      - rinha-default
    ports:
      - '54329:5432'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '160MB'

volumes:
  db-data:
    name: rinha-2024Q1-db-volume

networks:
  rinha-default:
    name: rinha-2024Q1-network